Added Lewis' requested changes to the Randoman + other changes
NoxxFlame/TTT-Jingle-Jam-Roles-2021 pull request #21
Opened 2022-03-12 10:01 UTC by TheStig294

- Added icons for the Randoman's shop, based on randomat categories
- Unbanned all events other than 'Infinite Credits' and 'That's Lame...'
- Prevented 'Infinite Credits' ever triggering while there is a Randoman alive
- At least 1 innocent biased, 1 fun/silly and 1 moderate impact randomat is guaranteed to be in the shop
- Added convar to change what categories of events are guaranteed
- Added randomat categories in the description
- Removed custom item markers on shop icons

2022-03-12 12:49 UTC, Malivil requested changes
Need to add the new convar to the README

2022-03-12 12:49 UTC, Malivil commented on gamemodes/terrortown/entities/entities/ttt_randoman_items/shared.lua
> +            local garunteedEventCategories = string.Explode(",", GetConVar("ttt_randoman_guaranteed_randomat_categories"):GetString())
```suggestion
            local guaranteedEventCategories = string.Explode(",", GetConVar("ttt_randoman_guaranteed_randomat_categories"):GetString())
```

2022-03-12 12:49 UTC, Malivil commented on gamemodes/terrortown/entities/entities/ttt_randoman_items/shared.lua
> +            local garunteedItemCount = #garunteedEventCategories
```suggestion
            local guaranteedItemCount = #guaranteedEventCategories
```

2022-03-12 12:49 UTC, Malivil commented on gamemodes/terrortown/entities/entities/ttt_randoman_items/shared.lua
> +                    if randomanItemCount <= garunteedItemCount then
```suggestion
                    if randomanItemCount <= guaranteedItemCount then
```

2022-03-12 12:49 UTC, Malivil commented on gamemodes/terrortown/entities/entities/ttt_randoman_items/shared.lua
> +                        category = garunteedEventCategories[randomanItemCount]
```suggestion
                        category = guaranteedEventCategories[randomanItemCount]
```

2022-03-12 12:49 UTC, Malivil commented on gamemodes/terrortown/entities/entities/ttt_randoman_items/shared.lua
> +                    -- or we're done with guranteed events, find a complete random one
```suggestion
                    -- or we're done with guaranteed events, find a completely random one
```

2022-03-12 12:49 UTC, Malivil commented on gamemodes/terrortown/entities/entities/ttt_randoman_items/shared.lua
> +                    -- There is garunteed to be one, as moderateimpact is the fallback category for an event without one
```suggestion
                    -- There is guaranteed to be one, as "moderateimpact" is the fallback category for an event without one
```

2022-03-13 07:00 UTC, TheStig294 commented
I also updated the workshop page with the new convar

2022-03-13 12:32 UTC, Malivil commented
> I also updated the workshop page with the new convar

I undid that as we shouldn't until it's actually been published.

2022-03-13 12:52 UTC, Malivil requested changes
What is "entityspawn" used for? Is that a category we were going to add?

2022-03-13 12:52 UTC, Malivil commented on lua/customroles/randoman.lua
> +    if event == "credits" and player.IsRoleLiving(ROLE_RANDOMAN) then return false end
There is an edge case where the Randoman is killed, someone else uses the Randomat and the "credits" event is triggered, and then the Randoman is resurrected.

If we want to handle that, the "IsRoleLiving" check would need to be replaced with a simple loop over `player.GetAll()`.

We don't need to worry about the same logic in `TTTRandomatShouldAuto` since that only happens at the start of the round.

2022-03-13 12:52 UTC, Malivil commented on gamemodes/terrortown/entities/entities/ttt_randoman_items/shared.lua
> +                    -- First put all guaranteed events in
```suggestion
                    -- First put all guaranteed events in
                    if randomanItemCount <= guaranteedItemCount then
                        category = guaranteedEventCategories[randomanItemCount]
                        local events = eventsByCategory[category]
                        table.Shuffle(events)

                        -- Find a random event in that category that is allowed to run
                        for _, categoryEvent in ipairs(events) do
                            if IsEventAllowed(categoryEvent) and Randomat:CanEventRun(categoryEvent, true) then
                                event = categoryEvent
                                break
                            end
                        end
                    end

                    -- If no events of that category are allowed to run,
                    -- or we're done with guaranteed events, find a complete random one
                    if not event then
                        event = Randomat:GetRandomEvent(true, IsEventAllowed)
                        category = "moderateimpact"

                        if istable(event.Categories) and not table.IsEmpty(event.Categories) then
                            category = event.Categories[1]
                        end
                    end

                    -- Update the icon and send the displayed category to the client
                    item.material = "vgui/ttt/roles/ran/items/" .. category .. ".png"
                    net.WriteString(category)
```

2022-03-13 12:52 UTC, Malivil commented on gamemodes/terrortown/entities/entities/ttt_randoman_items/shared.lua
> +                    -- First put all guaranteed events in
The suggested change thing in GitHub doesn't really show the diff well, but I moved the material assignment and `net.WriteString` to the bottom so it handles both cases. This reduces code repetition and also fixes the case where the `if not event` brand didn't have a material assigned on the server. Not sure if that's used, but at least it's consistent now.

2022-03-14 01:09 UTC, Malivil approved these changes

2022-03-14 01:09 UTC, Malivil commented on lua/customroles/randoman.lua
> +    if event.id == "credits" then
Oh yea, good catch. Didn't even notice that part.

2022-03-14 01:20 UTC, merged