Randoman Changes + Mal's changes
NoxxFlame/TTT-Jingle-Jam-Roles-2021 pull request #26
Opened 2022-03-20 07:37 UTC by TheStig294

(Mal)
Randoman

-     Added Future Proofing and Black Market Buyout to the blocked events while there is a Randoman
-     Added the ability to always have specific events in the Randoman shop, starting with "What Did I Find in My Pocket?"
-     Changed Randoman to have the radar and parasite cure in the shop, like all the other special detectives
-     Fixed events that are blocked by event history still being chosen for the Randoman shop even though they can't be started

Santa

-     Added Future Proofing to the blocked events while there is a Santa

(Me)
Randoman

-     Added guaranteed randomats convar
-     Removed radar again as wallhacks event is now guaranteed by default
-     Random minor linter cleanup
-     Removed credits event from banned convar by default as it can't show up in the shop anyway as it is now blocked

2022-03-20 14:53 UTC, Malivil requested changes
Missing README update for new convar

2022-03-20 14:53 UTC, Malivil commented on gamemodes/terrortown/entities/entities/ttt_randoman_items/shared.lua
> +table.remove(EquipmentItems[ROLE_RANDOMAN], tostring(EQUIP_ARMOR))
This does nothing because the Randoman is given armor for free by default

2022-03-20 14:53 UTC, Malivil commented on gamemodes/terrortown/entities/entities/ttt_randoman_items/shared.lua
> +        end
```suggestion
        else
            bannedEvents = {}
        end
```

2022-03-20 14:53 UTC, Malivil commented on gamemodes/terrortown/entities/entities/ttt_randoman_items/shared.lua
> +        end
```suggestion
        else
            forcedEvents = {}
        end
```

2022-03-21 01:27 UTC, TheStig294 commented on gamemodes/terrortown/entities/entities/ttt_randoman_items/shared.lua
> +table.remove(EquipmentItems[ROLE_RANDOMAN], tostring(EQUIP_ARMOR))
There's a convar that can add it: ttt_special_detectives_armor_loadout 0

2022-03-21 01:30 UTC, Malivil commented on gamemodes/terrortown/entities/entities/ttt_randoman_items/shared.lua
> +table.remove(EquipmentItems[ROLE_RANDOMAN], tostring(EQUIP_ARMOR))
Yea, fair enough... but then why do we not want them to be able to buy it?

2022-03-21 01:50 UTC, TheStig294 commented
> Missing README update for new convar

Always forget... How about now?

2022-03-21 02:19 UTC, Malivil commented on gamemodes/terrortown/entities/entities/ttt_randoman_items/shared.lua
> +table.remove(EquipmentItems[ROLE_RANDOMAN], tostring(EQUIP_ARMOR))
Fewer things in the shop means they are more likely to actually buy fun events

2022-03-21 02:25 UTC, Malivil approved these changes

2022-03-21 02:25 UTC, merged