Randoman beggar changes
NoxxFlame/TTT-Jingle-Jam-Roles-2021 pull request #45
Opened 2023-07-07 06:38 UTC by TheStig294

- Added ttt_randoman_event_on_unbought_death convar, which triggers a randomat if a randoman dies without buying anything

- Replaced the guaranteed "What did I find in my pocket?" event when the beggar is enabled, with simply adding the randomat SWEP to the randoman buy menu (Whether the beggar is enabled or not)

- Added ttt_randoman_give_used_randomats convar, which gives the randoman a "used randomat" on buying an event for converting the beggar, if the beggar is enabled

2023-07-07 11:32 UTC, Malivil commented
I don't like most of these changes. Here are a copy of my comments in your suggestion thread:

> I hate the concept of a useless item that does nothing except change the beggar. I hate it

> I think changing it so "What did I find in my pocket?" is always there (no matter whether Parasite is enabled or not) AND your idea of letting them buy a Randomat item is the way to go. Letting them buy a Randomat also solves the problems of "I don't want to choose" or "I don't like any of these choices"

> Your optional change of triggering a Randomat on their death if they haven't bought one is a good idea too

2023-07-08 08:33 UTC, NoxxFlame commented
I think all these changes sound good. I agree with mal that having a useless item in the shop doesn't sit well with me.
In general I am not a fan of changing established defaults unless there is a general consensus that most people would prefer the changes (e.g. old man/shadow reworks) so keeping "what did I find in my pocket" and adding the "choose and event" randomat seems like a good compromise.
The randomat on death option is also a fantastic idea!

2023-07-08 10:06 UTC, TheStig294 commented
Yea I'm just really afraid of the "What did I find in my pocket?" change that some players are now going to do nothing but buy that every time they are a Randoman like we saw Ben do already when that change was last in effect. I feel like with the randomat gift change it's redundant now.

Also unlike the randomat gift it's very unintuitive to be used for converting the beggar. The player has to realise 1. The event is in the buy menu, 2. The weapon they get can actually be used to convert the beggar, 3. That the beggar has to drop the weapon they just got, if the wepaon the Randoman is trying to give us in the same slot as the one they have.
Whereas the randomat gift has none of those problems. 1. Is solved by being able to see it in the buy menu immediately (has a unique icon). 2. Is solved by being an actual bought weapon, so of course it's going to convert the beggar. 3. Is solved by not giving the beggar an item in the process. 

This combined with the worry of people always buying the "What did I find in my pocket?", is why I don't like it, and why I made it so it didn't show up when there was a parasite cure originally.

I like having the randomat gift much much more than the "What did I find in my pocket?" event be guaranteed.

2023-07-08 11:45 UTC, Malivil requested changes
Your changes look good, only change needed is in the tutorial which isn't a new problem just a newly discovered problem =)

2023-07-08 11:45 UTC, Malivil commented on lua/customroles/randoman.lua
> +            if preventAutoRandomatCvar:GetBool() and ConVarExists("ttt_randomat_auto") and GetConVar("ttt_randomat_auto"):GetBool() then
Just realized this hasn't really worked on dedicated servers because neither of these convars are replicated and this code runs on the client

2023-07-08 12:06 UTC, Malivil approved these changes
LGTM

2023-07-09 05:22 UTC, NoxxFlame commented
Everything LGTM but after having a read through the discussion in more detail I did have one thought I wanted to quickly add.

> I like having the randomat gift much much more than the "What did I find in my pocket?" event be guaranteed.

After reading through this I can see your point with how using the randomat instead of the "what did I find in my pocket" event could be more intuitive so some players. As I mentioned before I don't love the idea of changing established defaults but I would definitely be okay with adding a convar (or maybe multiple convars) to enable/disable the different beggar solutions so that servers have the option to use whichever solution or combination of solutions they prefer.

2023-07-09 05:22 UTC, NoxxFlame approved these changes

2023-07-09 11:06 UTC, Malivil requested changes

2023-07-09 11:06 UTC, Malivil commented on lua/customroles/randoman.lua
> +                            self.EventArgs = {false, false, nil, 5}
Can we add a convar for that number of events?

2023-07-09 11:06 UTC, Malivil commented on lua/customroles/randoman.lua
>  ROLE.convars = {
Add the new convars to this list

2023-07-09 13:41 UTC, merged