Added the Randoman
NoxxFlame/TTT-Jingle-Jam-Roles-2021 pull request #8
Opened 2022-01-15 03:55 UTC by TheStig294

2022-01-15 04:30 UTC, Malivil requested changes

2022-01-15 04:30 UTC, Malivil commented on gamemodes/terrortown/entities/entities/ttt_randoman_items.lua
> +                for i, event in pairs(Randomat.ActiveEvents) do
This can be simplified by using `ply:IsRandoman() and Randomat:IsEventActive(item.eventid)`

2022-01-15 04:30 UTC, Malivil commented on gamemodes/terrortown/entities/entities/ttt_randoman_items.lua
> +        if player.IsRoleLiving(ROLE_RANDOMAN) or playerJoined then
IsRoleLiving is expensive so you should do `if playerJoined or player.IsRoleLiving(ROLE_RANDOMAN)` as a mini-optimization

2022-01-15 04:30 UTC, Malivil commented on gamemodes/terrortown/entities/entities/ttt_randoman_items.lua
> +                        name = "Randomat"
Would it be better to use a trimmed version of the event name rather than just the generic?

2022-01-15 04:30 UTC, Malivil commented on lua/customroles/randoman.lua
> +        type = ROLE_CONVAR_TYPE_TEXT
This should be `ROLE_CONVAR_TYPE_BOOL`

2022-01-15 04:30 UTC, Malivil commented on lua/customroles/randoman.lua
> +ROLE.translations = {}
These three lines can be deleted if you're not using them

2022-01-15 04:52 UTC, TheStig294 commented
How about now?

2022-01-15 12:39 UTC, Malivil requested changes
Just one small tweak and I think it's good to go =)

2022-01-15 12:39 UTC, Malivil commented on gamemodes/terrortown/entities/entities/ttt_randoman_items.lua
> +                        name = string.Left(name, 35)
Personally I would do `name = string.Left(name, 32) .. "..."` to show it's cut off

2022-01-15 13:29 UTC, Malivil approved these changes

2022-01-16 01:38 UTC, NoxxFlame approved these changes

2022-01-16 01:38 UTC, merged